<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
	    <TargetFrameworks>net9.0;net10.0;</TargetFrameworks>
		<OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="EncoderBenchmarks.cs" />
      <Compile Remove="StringEncodingOptimization.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
        <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
        <PackageReference Include="SpreadCheetah" Version="1.25.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Gooseberry.ExcelStreaming\Gooseberry.ExcelStreaming.csproj" />
      <ProjectReference Include="..\..\tests\Gooseberry.ExcelStreaming.Tests\Gooseberry.ExcelStreaming.Tests.csproj" /> 
    </ItemGroup>

   
</Project>
